"""empty message

Revision ID: 349efec71a80
Revises: 03c3f0c7cef8
Create Date: 2019-02-19 00:36:48.712013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '349efec71a80'
down_revision = '03c3f0c7cef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('blogs', 'date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('blogs', 'category')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.add_column('blogs', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('blogs', 'date_posted',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('subscribers')
    # ### end Alembic commands ###
