"""empty message

Revision ID: f5d3b90ead91
Revises: 39f980937a15
Create Date: 2019-02-18 11:57:11.095954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d3b90ead91'
down_revision = '39f980937a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('date_posted', sa.DateTime(), nullable=False))
    op.alter_column('blogs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blogs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('blogs', 'date_posted')
    # ### end Alembic commands ###
